### PR TITLE
Milestone 2: User interface

### PR DESCRIPTION
**Pull request by craigs40**
For this milestone, we've mapped out the general rules of Tic, Tac, Toe, what we need from players, and what we need to display for players.

### CODE REVIEW

**Review by cyonii — CHANGES_REQUESTED** [review]
# Statua: Changes Required ✍️

Hello team, great effort so far.

## To Highlight
- You have a simple and informative PR description 👌


## To Improve
You have done a nice job implementing the user interface for your app, but there are a few fixes you have to implement in order for this project to get approved.

- [x] Your user input should be validated so that empty input is NOT allowed, your program allows empty input, please fix this.
- [x] Your game enters into an infinite loop of collecting input from players. The game should declare a winner or declare the game a tie at some point _(note you don't need to compute this logically, you could make a random selection of the winner, or if the game is a tie)_.
- [x] Your mock flow should inform the player if their move is valid or not without actually computing it.

_**Also, remember a game of Tic Tac Toe has only 9 possible moves.**_


### You can find me on slack 👉 [CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) if you need further assistance or clarification. I'm always available and will be glad to help.

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# Status: Changes required :recycle: 

### Hello team, you have done good job so far, but we have to make some changes in order to better construct the game:

- [x] Empty input is still allowed, whenever a user puts an empty input the game auto selects 0 
- [x] The board should be displayed after each player move(but you do not have to compute which spots on the board are being taken), you can just repeat the board
- [x]  I get the following error while playing the game, kindly fix this Screenshot from 2021-03-07 01-29-28
- [x]  A loop is needed in this game (recommended is while but anything else will do ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
- [x] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:
```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```

### Please implement these changes and ask for another code review whenever you are ready

_**If you have any question related to the required changes feel free to text me on chat @GzimAsani**_

HAPPY CODING :computer: :desktop_computer:

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

### Great job! so far, really commendable 👏   👏   👏  
Let's make a few changes, and we will be done.

- [x] Like the previous TSE had mentioned, " The board should be displayed after each player move(but you do not have to compute which spots on the board are being taken), you can just repeat the board"
- [x] The input entered are not corresponding to the print statement. Example, I enter 1 and it shows 3
Screen Shot 2021-03-08 at 7 31 50 PM

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Review by cyonii — CHANGES_REQUESTED** [review]
# Status: Changes Required ✍️

Hello @GzimAsani,

Good job making the requested changes but it seems you have omitted one.

## To Improve
- [x] The previous TSE pointed out that the printed output is not corresponding with the input, see the image below where it asked John for input, John entered `1`, but it says John selected `0`. Please fix this so that your project can get approved to enable you carry on.
Output

Stay motivated and positive.

### You can find me on slack 👉 [CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) if you need further assistance or clarification. I'm always available and will be glad to help.

**Review by enaburekhan — APPROVED** [review]
# Status: Project Approved:heavy_check_mark:
**Hi team!
Nice one:clap::clap:. The game is working as expected.
Move on with the next milestone:walking:.**

[ Optional]

image.
Kindly change the number between 1 and 8 to 1 and 9.

Kindly drop your questions/comments :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan

**Pull request merged**
